### ISSUE TITLE
it can't visible in bootstrap modal window

### ISSUE THREAD

**Issue by vmkumar** [weareoutman/clockpicker#53]
clock picker can't displaying inside bootstrap modal popup window, it showing modal overlay behind..

**Comment by arall** [comment]
It can be fixed with this style:

``` css
.popover.clockpicker-popover{
    z-index: 1050;
}
```
