### ISSUE TITLE
standalone.css breaks user stylesheets

### ISSUE THREAD

**Issue by Chosko** [weareoutman/clockpicker#90]
I'm using clockpicker for my website but it's breaking my buttons due to this rule

``` css
.btn:hover, .btn:focus {
    color: #333;
    text-decoration: none;
}
```
